### PR TITLE
Update mean.asm

### PR DESCRIPTION
**Pull request by grosged**
a little bit faster

### CODE REVIEW

**Comment by PeterTillema** [comment]
This doesn't really work. The point is to get the carry flag from `add hl, de` to rotate back, to prevent things like `mean(-10,-2)` = `8388602`

**Comment by grosged** [comment]
Oh I see my mistake...
adding push af/pop af would be useless , as both versions would take exactly the same time.
But adding rla / rra  .... the overall would still be faster :)

**Comment by grosged** [comment]
rla & rra added ;)

**Comment by adriweb** [comment]
( @grosged you can edit your commit (with `git commit --amend ...`, or with a GUI tool) then `git push --force`, it will automatically update the PR from the commits on your source branch :) )

**Pull request merged**
