### PR TITLE
Added scroll

### PR DESCRIPTION
**Pull request by Ti64CLi**
I increased the number of program that ICE can display, and I added the scroll to this version

### CODE REVIEW

**Comment by LAX18** [comment]
LOL

**Comment by Ti64CLi** [comment]
It wasn't really what I wanted to do. It was more like a troll ^^
But, I'll change it

**Comment by Ti64CLi** [comment]
Don't you think it could be a good idea to display the version number in the description?

**Comment by PeterTillema** [comment]
No, the version number is already displayed in ICE itself.

**Pull request merged**
