### PR TITLE
Add comma

### PR DESCRIPTION
**Pull request by Ti64CLi**

### CODE REVIEW

**Comment by runer112** [comment]
I can't tell what this is supposed to be doing among the sea of junk commits and no description. At the very least, this PR definitely used the wrong branch as a base, or should not be targeting master.

**Comment by LAX18** [comment]
@runer112, as far aa I can tell, this PR fixes the hooks, which have already been fixed by PT_

**Comment by Ti64CLi** [comment]
Yeah, sorry for no description.
I modified the code, to add a comma after each det( and sum( function

**Comment by runer112** [comment]
Why are there so many commits and unrelated changes? As I said in my first comment, I believe you either used the wrong branch as a base, or should not be targeting master.

**Comment by Ti64CLi** [comment]
Because I first uploaded too much files (I forgot to delete the obj directory).
Then, I deleted the obj folder.

**Comment by runer112** [comment]
Look at the diff ("Files changed"). There's a lot of stuff there from some probably unintentional branch mixing.

**Comment by PeterTillema** [comment]
See https://github.com/PeterTillema/ICEhooks/pull/1

**Pull request closed without merging**
